name: fixedfundsflows
description: "Know where your money flows"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.5.4

dependencies:
  file_picker: ^10.1.8
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.19.0
  local_auth: ^2.3.0
  path_provider: ^2.1.5
  riverpod_annotation: ^2.6.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
